### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by 300682** [renever/cn_mooc_dl#1]
> python icourse163_dl.py -u
>  xxxx -p xxxxx "http://mooc.study.163.com/learn/NJU-100003"
> Login done...
> Traceback (most recent call last):
>   File "icourse163_dl.py", line 300, in <module>
>     main()
>   File "icourse163_dl.py", line 125, in main
>     'c0-param0':'number:' + cid.group(1),
> AttributeError: 'NoneType' object has no attribute 'group'

**Comment by 300682** [comment]
我地址搞错了。。。。
