### ISSUE TITLE
icourese163 下载失败

### ISSUE THREAD

**Issue by hacpai** [renever/cn_mooc_dl#4]
尝试下载 `http://mooc.study.163.com/course/ZJU-1000004001`

报了如下错误。

```
Login done...
Parsing..............Traceback (most recent call last):
  File "icourse163_dl.py", line 299, in <module>
    main()
  File "icourse163_dl.py", line 134, in main
    syllabus = parse_syllabus_icourse163(session, r3.content)
  File "icourse163_dl.py", line 276, in parse_syllabus_icourse163
    info = dict(re.findall(r"(?P<name>.*?):(?P<value>.*?),", s4.group('content')))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by hdvsyu** [comment]
出现同样的错误，不知怎么回事。。。

**Comment by jiangxiong66** [comment]
同样遇到了这个错误

**Comment by jinjingcai2014** [comment]
我也是遇到这个问题啊

**Comment by Lincolnhuj** [comment]
我现在login都不行了，是不是这个方法不好使了？

**Comment by zhiliang-lin** [comment]
同样登陆不了，有哪位大神知道原因吗？
